### ISSUE TITLE
Apparently requires a specific version of LLVM installed to build

### ISSUE THREAD

**Issue by crimsonskylark** [unknowntrojan/binja_coolsigmaker#1]
Hi, just a note for people attempting to build this. It seems you need LLVM 16 or 17 to successfuly build this. Using a newer version, such as 18, will generate an incomplete `bindings.rs` for `binaryninjacore-sys`,  leading to a failed build with thousands of linking errors. 

Previous discussion on this matter can be found here: https://github.com/Vector35/binaryninja-api/issues/5390

**Comment by unknowntrojan** [comment]
So that's why every one of my plugins started breaking. I'll add a note to the README tomorrow.
