### ISSUE TITLE
Built for different API

### ISSUE THREAD

**Issue by Max-109** [unknowntrojan/binja_coolsigmaker#4]
Hi, i get this error when i put the .dll file into the plugins folder 
**_Default] This plugin was built for an outdated core ABI (34). Please rebuild the plugin with the latest API (65)._** (Here i used build from June 15 2023)
Since I have a lot of errors during compiling, maybe could you build the latest build for windows? Thanks

**Comment by zkxjzmswkwl** [comment]
Surely there's one working sig plugin that works out of the box.

Surely.

**Comment by angelthorns** [comment]
Make sure to use rust nightly when compiling, this project requires it
```
rustup toolchain install nightly
rustup default nightly

git clone https://github.com/unknowntrojan/binja_coolsigmaker.git
cd binja_coolsigmaker
cargo build --release
```

**Comment by unknowntrojan** [comment]
@zkxjzmswkwl Surely there's a reverse engineer that can read instructions?
